<?xml version="1.0"?>
<package format="3">
  <name>idefix_simulation</name>
  <version>0.1.0</version>
  <description>Gazebo simulation for Idefix (worlds and sim launch).</description>
  <maintainer email="you@example.com">Guillaume Virgal</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>idefix_description</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>